lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: 900

  token_extractors:
    # ✅ LER DO COOKIE (OBRIGATÓRIO PARA /admin)
    cookie:
      enabled: true
      name: BEARER

    # ❌ (opcional) header desligado
    authorization_header:
      enabled: false
